[general]
shuffle_caption = true
resolution = 1024
batch_size = 2
caption_extension = '.txt'
enable_bucket = true
bucket_reso_steps = 32
max_bucket_reso = 1408
min_bucket_reso = 704


[[datasets]]

[[datasets.subsets]]
num_repeats = 1
image_dir = "/root/workspace/dataset"

